# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Test01.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cTest01.proto\x12\nTableProto\"6\n\rTest01Element\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0b\n\x03pos\x18\x03 \x03(\x03\"4\n\x06Test01\x12*\n\x07m_datas\x18\x01 \x03(\x0b\x32\x19.TableProto.Test01Elementb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Test01_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TEST01ELEMENT']._serialized_start=28
  _globals['_TEST01ELEMENT']._serialized_end=82
  _globals['_TEST01']._serialized_start=84
  _globals['_TEST01']._serialized_end=136
# @@protoc_insertion_point(module_scope)
